spring.application.name=notification-engine
# Enable H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console in Browser so we can see the data tables
spring.h2.console.enabled=true

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update